import Head from 'next/head'
import Login from '../components/Login'
import UserDashboard from '../components/UserDashboard'
import { useSelector, useDispatch } from "react-redux";
import { loadUser } from '../store/actions/authFunctions';
import { useEffect } from 'react';

export default function Home() {
  const dispatch= useDispatch()
  useEffect(() => {
    dispatch(loadUser());
  }, [dispatch]);
  const user = useSelector((state) => state.auth.user);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!user && <Login />}
      {user && <UserDashboard/>}
    </>
  )
}
